# -*- coding: utf-8 -*-
"""Even or odd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEAoabiUT5NE0dcO1ZKEgDh0SvFLlHPN
"""

#Write a program to check whether a number is even or odd.
user=int(input("Enter the number"))
if (user%2==0):
  print (f"{user} is an even number")
else:
  print (f"{user} is unfortunetly, an odd number :(")